[project]
id = "newsletter-platform"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lucassiroo-eng.github.io/newsletter-v1/"]

[auth.external.google]
enabled = true
